### PR TITLE
Add translations for new menu & rework locale date function

### PR DESCRIPTION
**Pull request by mickaelblondeau**

### CODE REVIEW

**Comment by primaeval** [comment]
Thanks. I tried it with Korean just to push the limits and the day conversion failed and wouldn't decode utf8. 

Could you have a look. 
https://github.com/primaeval/plugin.video.iptv.recorder/blob/31facfc484ecdc59159baf957d00ec1617b0a7e0/main.py#L691

**Comment by mickaelblondeau** [comment]
I tried with Korean, but I have invalid char ([]) everywhere, might be related to the theme/fonts

The error come from the given line ? Caused by title function ?

**Comment by primaeval** [comment]
Use ariel fonts to see the text. The error happens when the day function is used.

**Comment by mickaelblondeau** [comment]
I tried a lot a things, the best I got is something with no error but invalid text : https://i.imgur.com/nnHo40I.jpg

I'm not really familiar with enconding on python

**Comment by mickaelblondeau** [comment]
What do you think of using translation for day of week ? As everything is only translated to supported language, it's should be more consistant

**Comment by primaeval** [comment]
I'd like automatic day and date locale if possible but this is only fun software.

**Comment by primaeval** [comment]
I think I've fixed it in the latest commit. You need to call getlocale to find the encoding used in strftime to decode it with.

**Comment by mickaelblondeau** [comment]
Nice, it's working on my side too

I think there is an unused line here :
https://github.com/primaeval/plugin.video.iptv.recorder/commit/8b757df1837442f325560875d5ac3ae3b01dc497#diff-5bc02cefb3ea9e27f1a6776eabd1935dR682

**Comment by primaeval** [comment]
You're right thanks. Remnants of debugging.

I think it's about ready to release. What do you think?

**Comment by mickaelblondeau** [comment]
I'm OK with that, the only thing I'm seeing right now is the lack of informations on the loading process, something like Simple IPTV (percentage) could be good, but might not be required for everyone

**Comment by primaeval** [comment]
Try the latest commit. It needs a couple of strings translating.

Are you sure it records for all the rules with unicode characters? I've mainly been trying Record Once but I don't think I've tried unicode channel ids or names.

**Pull request merged**
